name: School Project Proxy with Cloudflare
on: workflow_dispatch

jobs:
  run-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Start MTProxy
        run: |
          # اجرای سرور پروکسی تلگرام روی پورت 443 داخلی
          docker run -d -p 443:443 --name mtp-server -e SECRET=ee00000000000000000000000000000000 telegrammessenger/proxy:latest
          
      - name: Install and Run Cloudflare Tunnel
        run: |
          # دانلود کردن ابزار کلادفلر (cloudflared)
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          
          # اجرای تونل به صورت موقت و نمایش لینک در کنسول
          # پورت 443 سرور داکر را به اینترنت وصل می‌کند
          cloudflared tunnel --url tcp://localhost:443
